// electron/updater.js — auto-update via electron-updater against GitHub
// Releases (repo: chan-dra1/echo-adaptive-voice-companion).
//
// How the end-to-end flow works (see electron/README.md for the full
// release runbook):
//   1. electron-builder.yml's `publish` block points at the GitHub repo.
//   2. `electron-builder --publish always` builds installers AND uploads
//      them (plus a generated latest.yml / latest-mac.yml manifest with
//      version + checksums) to a GitHub Release matching package.json's
//      version.
//   3. Every installed copy of Echo calls checkForUpdatesOnLaunch() below,
//      which asks GitHub "is there a release newer than my current
//      version?" by fetching that manifest.
//   4. If yes, electron-updater downloads the new installer in the
//      background and fires 'update-downloaded'. We notify the renderer
//      (which can show a "restart to update" banner); the update actually
//      applies the next time the app restarts (quitAndInstall(), or simply
//      the user quitting and relaunching — electron-updater swaps files on
//      next start either way).
//
// IMPORTANT — the unpackaged-dev guard: electron-updater throws
// synchronously ("Cannot find module 'app-update.yml'" / similar) if you
// call it in an app that wasn't built with electron-builder, because it
// looks for packaging metadata that only exists in a real build. Since this
// module is required from main.js on every launch (dev included), every
// exported function below no-ops immediately when `!app.isPackaged` so
// `npm run electron:dev` never crashes because an update check ran.

const { app, ipcMain } = require('electron');

let autoUpdater = null;
function getAutoUpdater() {
  if (!autoUpdater) {
    // Required lazily (not at module top-level) so that merely requiring
    // this file in dev never touches electron-updater's internals until
    // we've already confirmed we're in a packaged build.
    autoUpdater = require('electron-updater').autoUpdater;
    autoUpdater.autoDownload = true; // download automatically once an update is found
    autoUpdater.autoInstallOnAppQuit = true; // apply on next natural quit if the user never clicks "restart now"

    autoUpdater.on('checking-for-update', () => broadcast('checking'));
    autoUpdater.on('update-available', (info) => broadcast('available', info.version));
    autoUpdater.on('update-not-available', () => broadcast('not-available'));
    autoUpdater.on('download-progress', (progress) => broadcast('downloading', Math.round(progress.percent)));
    autoUpdater.on('update-downloaded', (info) => broadcast('downloaded', info.version));
    autoUpdater.on('error', (err) => broadcast('error', String(err)));
  }
  return autoUpdater;
}

let getWindow = () => null;

// Sends update lifecycle events to the renderer via the 'echo:update-status'
// channel preload.js subscribes to (onUpdateStatus). `status` is one of:
// 'checking' | 'available' | 'not-available' | 'downloading' | 'downloaded' | 'error'.
function broadcast(status, detail) {
  const win = getWindow();
  if (win && !win.isDestroyed()) {
    win.webContents.send('echo:update-status', { status, detail });
  }
  console.log(`[updater] ${status}${detail !== undefined ? ` (${detail})` : ''}`);
}

// Call once on app launch. `windowGetter` is a `() => BrowserWindow | null`
// thunk (rather than a direct reference) because main.js calls this before
// the window necessarily exists in every edge case, and because the window
// can be recreated (macOS dock click) — we always want the *current* one.
function checkForUpdatesOnLaunch(windowGetter) {
  getWindow = windowGetter;

  if (!app.isPackaged) {
    // Dev/unpackaged run (`npm run electron:dev` or bare `electron .`).
    // electron-updater has nothing to check against here — there's no
    // app-update.yml generated by electron-builder, and "updating" a dev
    // checkout makes no sense anyway. No-op quietly rather than throwing.
    console.log('[updater] skipped (not a packaged build)');
    return;
  }

  checkForUpdates(windowGetter);
}

// Manual trigger (e.g. a "Check for Updates" menu item / settings button),
// shares the same guard as the launch-time check.
function checkForUpdates(windowGetter) {
  if (windowGetter) getWindow = windowGetter;

  if (!app.isPackaged) {
    broadcast('not-available'); // keep the UI honest in dev rather than silently doing nothing
    return;
  }

  try {
    getAutoUpdater().checkForUpdates();
  } catch (err) {
    // Network failures, GitHub being unreachable, no matching release yet,
    // etc. should never be fatal — Echo works fine on its current version.
    console.error('[updater] checkForUpdates failed:', err);
    broadcast('error', String(err));
  }
}

module.exports = { checkForUpdatesOnLaunch, checkForUpdates };
