/**
 * dynamicSkillService.ts
 *
 * Stores user-approved "dynamic" skills in IndexedDB and registers them
 * into agentSkillService on load. A dynamic skill is a small JS module
 * generated by the LLM in response to a `propose_new_skill` tool call.
 *
 * Each skill has:
 *   - id, name, description
 *   - schema: a Gemini FunctionDeclaration (passed straight through)
 *   - jsCode: the body of the skill, executed inside a sandboxed worker.
 *             The code must end with an `export`-like assignment to
 *             `skill = { execute(toolName, args) { ... } }` — the
 *             worker harness expects a top-level `skill` symbol.
 *   - permissions: requested + approved capability whitelists.
 *   - createdAt, approvedAt
 */

import { openDB, IDBPDatabase } from 'idb';
import type { FunctionDeclaration } from '@google/genai';
import { agentSkillService, Skill, ToolDefinition } from './agentSkillService';
import { getOrCreateWorker, disposeWorker, SkillPermissions } from './dynamicSkillRunner';

export interface DynamicSkill {
    id: string;
    name: string;
    description: string;
    schema: FunctionDeclaration;
    jsCode: string;
    permissions: SkillPermissions;
    createdAt: number;
    approvedAt: number;
}

const DB_NAME = 'echo-dynamic-skills';
const STORE = 'skills';

let dbPromise: Promise<IDBPDatabase> | null = null;
function db(): Promise<IDBPDatabase> {
    if (!dbPromise) {
        dbPromise = openDB(DB_NAME, 1, {
            upgrade(database) {
                if (!database.objectStoreNames.contains(STORE)) {
                    database.createObjectStore(STORE, { keyPath: 'id' });
                }
            },
        });
    }
    return dbPromise;
}

function toSkill(ds: DynamicSkill): Skill {
    return {
        name: `dyn:${ds.name}`,
        description: ds.description,
        tools: [ds.schema as ToolDefinition],
        execute: async (toolName: string, args: any) => {
            if (toolName !== ds.schema.name) {
                return { error: `Tool ${toolName} not provided by dynamic skill ${ds.name}` };
            }
            try {
                const worker = getOrCreateWorker(ds.id, ds.jsCode, ds.permissions);
                const result = await worker.invoke(toolName, args);
                return result;
            } catch (e: any) {
                return { error: e?.message || String(e) };
            }
        },
    };
}

export const dynamicSkillService = {
    async list(): Promise<DynamicSkill[]> {
        try {
            const conn = await db();
            return (await conn.getAll(STORE)) as DynamicSkill[];
        } catch (e) {
            console.error('[dynamicSkillService] list failed:', e);
            return [];
        }
    },

    async get(id: string): Promise<DynamicSkill | undefined> {
        const conn = await db();
        return (await conn.get(STORE, id)) as DynamicSkill | undefined;
    },

    async upsert(skill: DynamicSkill): Promise<void> {
        const conn = await db();
        await conn.put(STORE, skill);
        // re-register so the new code is picked up
        disposeWorker(skill.id);
        agentSkillService.registerSkill(toSkill(skill));
    },

    async delete(id: string): Promise<void> {
        const conn = await db();
        await conn.delete(STORE, id);
        disposeWorker(id);
    },

    async loadAndRegisterAll(): Promise<void> {
        const items = await this.list();
        for (const item of items) {
            try {
                agentSkillService.registerSkill(toSkill(item));
            } catch (e) {
                console.warn('[dynamicSkillService] register failed for', item.name, e);
            }
        }
        console.log(`[dynamicSkillService] Loaded ${items.length} dynamic skill(s).`);
    },
};
